services:
  app:
    build: .
    working_dir: /var/www/html
    environment:
      # Let IDE map paths
      PHP_IDE_CONFIG: "serverName=laravel-api-starter"

      XDEBUG_MODE: "debug,develop"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"

    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor

    ports:
      - "8000:8000"

    # Needed on Linux so `host.docker.internal` resolves
    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_auth
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel123
    ports:
      - "3306:3306"
